In [1]:
import tensorflow as tf
import numpy as np

In [2]:
xy = np.loadtxt('./logistic.dat', unpack=True, dtype='float32')
x_data = xy[0:-1]
y_data = xy[-1]

In [3]:
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

W = tf.Variable(tf.random_uniform([1, len(x_data)], -1.0, 1.0))

h = tf.matmul(W, X)
hypothesis = tf.div(1., 1. + tf.exp(-h))

cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))

In [4]:
a = tf.Variable(0.1)  # learning rate, alpha
optimizer = tf.train.GradientDescentOptimizer(a)
train = optimizer.minimize(cost)  # goal is minimize cost

init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)

for step in range(10000):
    sess.run(train, feed_dict={X: x_data, Y: y_data})
    if step % 100 == 0:
        print((step, sess.run(cost, feed_dict={X: x_data, Y: y_data}), sess.run(W)))

(0, 0.69244617, array([[-0.44698417,  0.56535155, -0.24234931]], dtype=float32))
(100, 0.50953078, array([[-1.38380301,  0.13240102,  0.32498088]], dtype=float32))
(200, 0.45830154, array([[-2.08717704,  0.18951525,  0.43338704]], dtype=float32))
(300, 0.42690668, array([[-2.63873649,  0.24241963,  0.51071304]], dtype=float32))
(400, 0.40619192, array([[-3.08693218,  0.28342423,  0.5751515 ]], dtype=float32))
(500, 0.39171207, array([[-3.46173072,  0.31579974,  0.63050359]], dtype=float32))
(600, 0.38112172, array([[-3.78229165,  0.34195262,  0.67896569]], dtype=float32))
(700, 0.37309316, array([[-4.06140661,  0.36349553,  0.72202319]], dtype=float32))
(800, 0.36682844, array([[-4.30796003,  0.3815338 ,  0.76073122]], dtype=float32))
(900, 0.36182287, array([[-4.52833557,  0.39684749,  0.79586625]], dtype=float32))
(1000, 0.35774407, array([[-4.72725534,  0.41000184,  0.82801503]], dtype=float32))
(1100, 0.35436466, array([[-4.90830612,  0.42141655,  0.85763252]], dtype=float32))
(120

In [5]:
print(sess.run(hypothesis, feed_dict={X: [[1], [2], [2]]}) > 0.5)
print(sess.run(hypothesis, feed_dict={X: [[1], [5], [5]]}) > 0.5)

[[False]]
[[ True]]


In [6]:
x_data

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  3.,  3.,  5.,  7.,  2.],
       [ 1.,  2.,  5.,  5.,  5.,  5.]], dtype=float32)

In [7]:
y_data

array([ 0.,  0.,  0.,  1.,  1.,  1.], dtype=float32)

In [8]:
sess.run(tf.matmul(W, x_data))

array([[-6.29173708, -4.13599014,  0.66983986,  1.7774477 ,  2.88505507,
         0.11603642]], dtype=float32)